POST http://localhost:3008/api/greetings
Content-Type: application/json

{
    "greeting": "Goeie More",
    "language": "Afrikaans"
}

###

GET http://localhost:3008/api/greetings

###

GET https://sqlite-greetings-using-migrations-and.onrender.com/api/greetings